### ISSUE TITLE
Predicted local player input needs to be properly separated

### ISSUE THREAD

**Issue by organicpencil** [pqftgs/bge-netplay#12]
The current implementation is confusing, jittery, and likely broken with actual latency.
This was addressed in the parent project (Rise of the Undead Cubes) but the fix was rather dirty.

**Comment by pqftgs** [comment]
The implemented fix comes with a minor limitation, setting ignoreOwner = True will block input to users that share the same component simultaneously.

However I consider this to be a rare (if not non-existent) use-case.
Generally shared components **shouldn't be using local input prediction anyway**, lest you have nasty conflicts with the other player.
